Remove lombok annotations from Quantity class
fabric8io/kubernetes-client pull request #2532
Opened 2020-10-07 07:31 UTC by stanlyDoge

Signed-off-by: Stanislav Knot <sknot@redhat.com>

## Description
Quantity class has these lombok annotations in the header:
1. `ToString`
2. `EqualsAndHashCode`

but this class is also implementing methods `toString` and `equals`. 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2020-10-07 07:33 UTC, oscerd requested changes
Any particular reason to remove those?

2020-10-07 07:38 UTC, stanlyDoge commented
Just for cleaner build
```COMPILE> [ERROR] /home/kubernetes-client/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java:[48,1] Not generating toString(): A method with that name already exists
COMPILE> [ERROR] /home/kubernetes-client/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java:[49,1] Not generating equals and hashCode: A method with one of those names already exists. (Either both or none of these methods will be generated).
```

2020-10-07 07:38 UTC, oscerd approved these changes

2020-10-07 08:15 UTC, rohanKanojia approved these changes

2020-10-08 04:59 UTC, manusa approved these changes

2020-10-08 07:45 UTC, rohanKanojia commented
[merge]

2020-10-08 08:10 UTC, merged