Add chaos mesh (chaos-mesh.org) client externsion
fabric8io/kubernetes-client pull request #2556
Opened 2020-10-21 16:42 UTC by hypnoce

## Description

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2020-10-21 16:52 UTC, rohanKanojia commented
This projects uses Apache 2.0 License. You would need to add license headers using `mvn -N license:format`

2020-10-21 16:56 UTC, oscerd requested changes
Just a couple of typo. It seems to be ok. 

At some point I guess we may need to host extensions in a separate repository, because they could explode in terms of number.

2020-10-21 16:56 UTC, oscerd commented on extensions/chaosmesh/client/pom.xml
> +              <name>Snowdrop :: Chaos Mrsh ::Bom</name>
I guess it should be Chaos Mesh :: Bom

2020-10-21 16:56 UTC, oscerd commented on extensions/chaosmesh/client/pom.xml
> +              <name>Snowdrop :: Chaos Mesh ::Bom with Dependencies</name>
It should be Chaos Mesh :: Bom with Dependencies

2020-10-21 17:36 UTC, hypnoce commented
@oscerd I think the sonar analysis is a bit wrong. Running locally shows coverage data.

2020-10-21 18:05 UTC, hypnoce commented
Let me know if you need more work from my side. Thanks !

2020-10-22 05:32 UTC, manusa commented
> @oscerd I think the sonar analysis is a bit wrong. Running locally shows coverage data (not 100% coverage though).

Coverage is calculated only for **unit** tests within the same module.

2020-10-27 03:51 UTC, zhouqiang-cl commented
@hypnoce @manusa Chaos Mesh maintainer here, thank you very much for this PR. If need any assistance from Chaos Mesh team, please let me know

Thank you again

2020-10-27 06:22 UTC, oscerd approved these changes

2020-10-27 14:39 UTC, iocanel approved these changes

2020-10-27 14:39 UTC, iocanel commented on extensions/chaosmesh/examples/src/main/java/io/fabric8/chaosmesh/examples/CreateIoChaos.java
> +  //    cron: "@every 10m"
+1

2020-11-02 08:14 UTC, rohanKanojia commented
@hypnoce: Thanks a lot for your PR. It looks really good to be merged. Are you(or someone from your team) planning to write a blogpost about this extension whenever it gets merged?

2020-11-03 15:46 UTC, hypnoce commented
> @hypnoce: Thanks a lot for your PR. It looks really good to be merged. Are you(or someone from your team) planning to write a blogpost about this extension whenever it gets merged?

@rohanKanojia do you have any blog in mind ?
If there is there anything for this PR to be merged, let me know. Thanks

2020-11-03 16:28 UTC, rohanKanojia commented
@hypnoce: Sorry for not being clear. I was asking if you plan to write a blogpost about this Chaos Mesh extension. I wrote two blog posts about Knative[0] and Tekton[1] extensions few months ago. Maybe you can write a similar one for this one?

Regarding getting this PR merged, it's pending on review from  @manusa . Whenever he approves it, it will be merged.

[0] https://rohaan.medium.com/accessing-knative-rest-api-using-fabric8-knative-client-443a16ac43f7
[1] https://itnext.io/access-tekton-pipelines-in-java-using-fabric8-tekton-client-bd727bd5806a

2020-11-09 16:15 UTC, manusa approved these changes

2020-11-11 06:24 UTC, rohanKanojia approved these changes

2020-11-16 13:41 UTC, rohanKanojia commented
@hypnoce : Hi, Could you please rebase this branch with master? We have made some breaking changes in kubernetes Client DSL #2566 .

2020-11-16 13:42 UTC, hypnoce commented
> @hypnoce : Hi, Could you please rebase this branch with master? We have made some breaking changes in kubernetes Client DSL #2566 .

done

2020-11-18 15:38 UTC, hypnoce commented
@rohanKanojia anything else I can do ?

2020-11-18 15:43 UTC, rohanKanojia commented
@hypnoce : Hi, Sorry for the delay. Could you please modify the entry in CHANGELOG and move it to `5.0-SNAPSHOT` section? I think we can proceed with merge.

2020-11-18 16:21 UTC, rohanKanojia commented
[merge]

2020-11-19 06:32 UTC, rohanKanojia commented
[merge]

2020-11-19 06:57 UTC, merged