Add an integration test for BuildConfig instantiation
fabric8io/kubernetes-client pull request #2689
Opened 2020-12-22 19:05 UTC by rohanKanojia

We instantiate BuildConfig in Eclipse JKube while doing S2I builds. Adding an integration test for that so that we don't break this again in the future.

Related to https://github.com/fabric8io/kubernetes-client/issues/2668

## Description

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2020-12-22 19:23 UTC, oscerd approved these changes

2020-12-23 05:56 UTC, manusa requested changes
Given there is a setup and clean up phase, and that there is a lot of logic here (Watcher implementation, etc.)
It would make more sense to move this to its own test suite (e.g. `BuildConfigWatchIT`)

2020-12-23 06:53 UTC, manusa approved these changes

2020-12-23 07:40 UTC, manusa commented
[merge]

2020-12-23 08:07 UTC, merged