[wip] upgrade to sundrio 0.40-SNAPSHOT
fabric8io/kubernetes-client pull request #3114
Opened 2021-05-13 08:37 UTC by iocanel

-------
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [*] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [*] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2021-05-13 13:01 UTC, oscerd approved these changes

2021-05-13 13:19 UTC, manusa commented
![image](https://user-images.githubusercontent.com/488391/118131231-8cc94d80-b3fe-11eb-8d7d-2ab84bc888fd.png)
Cool!

2021-05-13 13:24 UTC, manusa approved these changes
LGTM, thx!

2021-05-13 17:06 UTC, manusa commented
Fixes #3102

2021-05-13 19:00 UTC, metacosm requested changes

2021-05-13 19:13 UTC, iocanel commented on crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
> +      CustomResourceColumnDefinition columnDefinition = printerColumns.stream().filter(p -> p.getJsonPath().equals(".spec.category")).findFirst().orElse(null);
Then the ordering of printer columns is broken.

2021-05-13 19:15 UTC, iocanel commented on crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
> +      CustomResourceColumnDefinition columnDefinition = printerColumns.stream().filter(p -> p.getJsonPath().equals(".spec.category")).findFirst().orElse(null);
On second thought, I don't see how is there such thing as order of printer columns? A printer columns may be defined anywhere in the graph, how can you guarantee the order?

2021-05-13 19:23 UTC, metacosm commented on crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
> +      CustomResourceColumnDefinition columnDefinition = printerColumns.stream().filter(p -> p.getJsonPath().equals(".spec.category")).findFirst().orElse(null);
That was the goal of this PR: https://github.com/fabric8io/kubernetes-client/pull/3071/files

2021-05-13 19:26 UTC, metacosm requested changes

2021-05-13 19:26 UTC, metacosm commented on crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java
> +    if (config.specClassName().isPresent()) {
Wrong method call: this should be `config.statusClassName()`.

2021-05-13 19:29 UTC, metacosm commented on crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
> +      CustomResourceColumnDefinition columnDefinition = printerColumns.stream().filter(p -> p.getJsonPath().equals(".spec.category")).findFirst().orElse(null);
Cf https://github.com/fabric8io/kubernetes-client/blob/62e2bcd260e7bdc017eb19aec2a8e2adbdbdeba6/crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java#L207

2021-05-14 06:37 UTC, iocanel commented on crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
> +      CustomResourceColumnDefinition columnDefinition = printerColumns.stream().filter(p -> p.getJsonPath().equals(".spec.category")).findFirst().orElse(null);
That pull request may or not work, given that it was applied on a test that was disabled and no other test has been provided.
I am going to revert that change and align the test in order to pass.

2021-05-14 07:04 UTC, iocanel commented on crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
> +      CustomResourceColumnDefinition columnDefinition = printerColumns.stream().filter(p -> p.getJsonPath().equals(".spec.category")).findFirst().orElse(null);
Fixed the `SortPrinterColumnDecorator` and reverted that change.

2021-05-14 07:04 UTC, iocanel commented on crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
> +      columnDefinition = printerColumns.stream().filter(p -> p.getJsonPath().equals(".spec.excluded")).findFirst().orElse(null);
Fixed the `SortPrinterColumnDecorator` and reverted that change.

2021-05-14 07:05 UTC, iocanel commented
@manusa: Addressed all concerns raised by @metacosm.

2021-05-14 07:46 UTC, merged

2021-05-14 07:53 UTC, metacosm commented
Out of curiosity what was wrong with the printer columns sorting?

2021-05-14 09:28 UTC, manusa commented
After analyzing the generated code with 0.40.0 and 0.30.6, these are some of the differences:

| 0.40.0 | 0.30.6 | Comments |
| -------- | -------- | --------------- |
| Canonical class references | imports | Improved resiliency |
| build methods use ternary+streams | build methods have if-statements+for-loops | For all cases except for `Set` the resulting collection is added to a new ArrayList. For the `Set` case this might be a problem if the resulting collection is manipulated by the consuming code |
| canVisit template probably has end-of-line spaces | | nit: would be good to remove those spaces |
| Fluent type interface is now less restrictive `Fluent<F>` | Fluent type interface is more restrictive `Fluent<F extends Fluent<F>>` | As agreed with @iocanel this is a bug that needs to be addressed |
| Visitor interface has no longer the `@FunctionalInterface` annotation | | |
| `withNewXXX(StringBuffer)` / `withNewXXX(StringBuilder)` methods lost | | It's very unlikely that any consuming code is making use of this methods, it seems reasonable to keep this breaking change |