Fix for #3243, #3244 Prevent data loss when client provides pipes to exec
fabric8io/kubernetes-client pull request #3245
Opened 2021-06-15 09:08 UTC by pdudits

## Description

This fixes data loss when using `PipedInputStream` to pump output from exec command. Since this user-provided resource was auto-closed on websocket connection close, client was unable to read contents of the buffer after last chunk was received.

Handling of `PipedOutputStream` provided for `stdin` was changed in same fashion, although the impact there is not that big due to how the pair is implemented.

I've run the unit tests in my Windows environment and fixed any issues with tests I encountered there (none of them were related to pipes, rather OS quirks).

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2021-06-15 09:17 UTC, oscerd approved these changes

2021-06-15 12:27 UTC, shawkins requested changes
LGTM, but can the imports be left in their original position?  There's another pr open that this will introduce conflicts with.

2021-06-15 13:24 UTC, pdudits commented
I didn't notice I had that activated in the IDE, sorry.

Import sections have been reset.

2021-06-15 13:28 UTC, iocanel commented on kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
> -            toClose.add(out);
+1: You should never ever be your responsibility to close a stream that was handed out to you.

2021-06-15 13:29 UTC, iocanel approved these changes
LGTM, thanks a lot!

2021-06-16 06:10 UTC, rohanKanojia approved these changes

2021-06-16 11:31 UTC, shawkins approved these changes
LGTM

2021-06-21 13:35 UTC, manusa approved these changes
LGTM, thx!

2021-06-21 15:06 UTC, merged