Pb k8s
fabric8io/kubernetes-client pull request #3435
Opened 2021-09-01 09:58 UTC by pangbin0502

![图片](https://user-images.githubusercontent.com/38174581/131651854-79744a47-5182-4205-a0f0-1a9457c627ec.png)
reply this, more

2021-09-07 04:43 UTC, rohanKanojia approved these changes

2021-09-21 11:10 UTC, manusa commented
```
2021-09-07T05:17:56.6189996Z Exit code: 1 - /home/runner/work/kubernetes-client/kubernetes-client/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java:49: error: invalid use of @param
2021-09-07T05:17:56.6191528Z  * @param args Either "--cluster" or namespace name.
```

2023-01-23 13:48 UTC, sunix requested changes

2023-01-23 13:48 UTC, sunix commented on kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
> + * @param args Either "--cluster" or namespace name.
param to remove

2023-02-28 06:21 UTC, closed without merging