Update the crd-generator/README.md file
fabric8io/kubernetes-client pull request #3457
Opened 2021-09-09 18:21 UTC by kanedafromparis

dependencies have change from one (io.fabric8:crd-generator) to two (io.fabric8:crd-generator-api & io.fabric8:crd-generator-apt)

## Description

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2021-09-09 19:24 UTC, oscerd approved these changes

2021-09-10 05:59 UTC, metacosm requested changes

2021-09-10 05:59 UTC, metacosm commented on crd-generator/README.md
> +  and `io.fabric8:crd-generator-apt` dependencies to your project (with the suggested `compile` scope)
You don't need to include `crd-generator-api` if you use `crd-generator-apt`: that last one should be sufficient. The API module is only needed for programmatic access to the CRD generation.

2021-09-10 09:06 UTC, metacosm requested changes

2021-09-10 09:06 UTC, metacosm commented on crd-generator/README.md
> +- CRDs are automatically generated at compile-time if you include `io.fabric8:crd-generator-api`
This still isn't correct. The dependency to use is `crd-generator-apt` if you want the CRD automatically generated at compile-time.

2021-09-10 12:03 UTC, metacosm commented on CHANGELOG.md
> +* Fix #3456: io.fabric8:crd-generator ReadMe.md
```suggestion
* Fix #3456: io.fabric8:crd-generator README should reference crd-generator-apt instead of now removed crd-generator artifact
```

2021-09-10 12:04 UTC, metacosm approved these changes

2021-09-10 12:05 UTC, metacosm commented
This will need to be squashed :)

2021-09-21 13:36 UTC, manusa approved these changes

2021-09-21 14:18 UTC, merged