fix #3957: Lister `onOpen` should be called before marking the connection open
fabric8io/kubernetes-client pull request #3958
Opened 2022-03-10 08:43 UTC by AdrianFarmadin

## Description
In `PodOperationsImpl` class the `buildAsync` method is called with `ExecWebSocketListener`.
The `ExecWebSocketListener` is opening `outputPipe` and `errorPipe` in `onOpen`.
If the `future` is completed before the `outputPipe` and `errorPipe` are open, then the consumer can read from the pipes before  they are open. 

The pipes should be open first and then the future should be marked as complete. 

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2022-03-10 09:30 UTC, oscerd approved these changes

2022-03-10 12:38 UTC, shawkins requested changes
LGTM - but this primarily needs applied to master and can there be an update to the javadocs of our WebSocket.Builder.buildAsync to explicitly state the expectation that onOpen is called first - just to make sure that if for whatever reason we can't honor that we'll have to change the calling logic.

This happened because of eliminating the additional wait logic that was in the ExecWebSocketListener, so this is applicable to 5.11 as well.  

The JDK client behavior is consistent with this change - the returned future from buildAsync will not be completed until after onOpen has been called (but that is not explicitly called out in the javadocs).

2022-03-14 08:15 UTC, AdrianFarmadin commented
I added javadocs.

Should I create pull requests for master and 5.11 as well?

2022-03-14 22:44 UTC, shawkins approved these changes
LGTM

@manusa how do you usually handle porting to other branches - is that something that you usually just cherry-pick and update from there?

2022-03-22 12:56 UTC, manusa commented
> LGTM
> 
> @manusa how do you usually handle porting to other branches - is that something that you usually just cherry-pick and update from there?

I switched this to master and added the backport label. I'm still not sure how I'm going to handle these ones, since some of the [selected changes](https://github.com/fabric8io/kubernetes-client/labels/5.12.x) are going to be hard to move to 5.12.

2022-03-22 13:47 UTC, manusa approved these changes

2022-03-22 17:19 UTC, merged