Update chaos mesh to v2.1.3
fabric8io/kubernetes-client pull request #3967
Opened 2022-03-14 13:21 UTC by hypnoce

## Description

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2022-03-14 13:24 UTC, hypnoce commented
@iocanel I intentionally left this PR breaking the build. The problem is that one of the fields in the chaosmesh CRD has the name "class". While this works fine with jsonchema2pojo, it breaks sundr. There are many ways to fix this, I wanted to get your feedback first.

2022-03-23 14:56 UTC, hypnoce commented
@oscerd @iocanel let me know how you prefer to move forward with this. Thanks

2022-07-28 09:12 UTC, manusa commented
Hi @hypnoce 
This PR never made it to the ready phase and is now quite updated. Are you still working on it?

2022-08-29 07:40 UTC, manusa commented on CHANGELOG.md
> +* Update chaos-mesh extension to v2.1.3. Add PodHttpChaos, GCPChaos, BlockChaos and PhysicalMachineChaos.
Apparently the capitalization of some generated class names has changed. We should add a note about this or revert this change.

2022-08-29 09:23 UTC, manusa approved these changes

2022-08-29 12:39 UTC, manusa commented
After https://github.com/fabric8io/kubernetes-client/pull/4358, the [fix (extensions/chaosmesh) : Use hand written JVMChaosSpec and related classes](https://github.com/fabric8io/kubernetes-client/pull/3967/commits/208d9ae718cd216efd6ea5fac99e72b213200b85) should not be necessary.
Please rebase and remove it.

2022-08-29 12:39 UTC, manusa requested changes
See previous comment

2022-08-30 05:16 UTC, manusa approved these changes

2022-08-30 05:16 UTC, merged