set bignumbermode when creating tar for upload to pod
fabric8io/kubernetes-client pull request #5186
Opened 2023-05-31 06:40 UTC by sorend

## Description

Set bignumbermode when creating tar files for uploading to pod.

Bignumbermode is required to support large UIDs, which are commonly used on e.g. Openshift.

Integration tests already do the same thing:
https://github.com/fabric8io/kubernetes-client/blob/f6ea58c62e818a53f6c261a1c7a9549c138c8d88/kubernetes-itests/src/test/java/io/fabric8/openshift/BuildIT.java#L125

## Type of change

Bugfix, to avoid this type of error:
```
Caused by: java.lang.IllegalArgumentException: user id '1000990000' is too big ( > 2097151 ).
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:406)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:400)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:418)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:592)
	at io.fabric8.kubernetes.client.dsl.internal.uploadable.PodUpload.addFileToTar(PodUpload.java:178)
```

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

2023-05-31 07:38 UTC, manusa approved these changes

2023-05-31 07:45 UTC, oscerd approved these changes

2023-05-31 07:46 UTC, rohanKanojia approved these changes

2023-05-31 08:22 UTC, manusa requested changes
Please check failing tests

2023-07-04 08:56 UTC, sunix commented
@sorend would it be possible to update the PR (rebase to master)? Let us know

2023-07-19 11:50 UTC, manusa approved these changes

2023-07-19 17:24 UTC, merged