chore (kubernetes-model-generator) : Update Kubernetes Model to v1.27.3 (#5056)
fabric8io/kubernetes-client pull request #5270
Opened 2023-06-21 09:13 UTC by rohanKanojia

## Description
Fix #5056 

This PR only focused on adding model types. If we want to add DSL support to KubernetesClient, I'll do that in a follow up PR

### Added Resources:
- `networking.k8s.io/v1alpha1` IPAddress
- `networking.k8s.io/v1alpha1` ClusterCIDR
- `internal.apiserver.k8s.io/v1alpha1` StorageVersion
- `certificates.k8s.io/v1alpha1` ClusterTrustBundle
- `authentication.k8s.io/v1beta1` SelfSubjectReview

### Moved Resources:
- `io.fabric8.kubernetes.api.model.resource.v1alpha1.PodSchedulingContext` -> - `io.fabric8.kubernetes.api.model.resource.v1alpha2.PodSchedulingContext`
- `io.fabric8.kubernetes.api.model.resource.v1alpha1.ResourceClaim` -> - `io.fabric8.kubernetes.api.model.resource.v1alpha2.ResourceClaim`
- `io.fabric8.kubernetes.api.model.resource.v1alpha1.ResourceClaimTemplate` -> `io.fabric8.kubernetes.api.model.resource.v1alpha2.ResourceClaimTemplate`
- `io.fabric8.kubernetes.api.model.resource.v1alpha1.ResourceClass` -> `io.fabric8.kubernetes.api.model.resource.v1alpha2.ResourceClass`

### Go Module Bumps:
- Bump `k8s.io/api` to `v0.27.3`
- Bump `k8s.io/apiextensions-apiserver` to `v0.27.3`
- Bump `k8s.io/apimachinery` to `v0.27.3`
- Bump `k8s.io/kube-aggregator` to `v0.27.3`
- Bump `k8s.io/metrics` to `v0.27.3`
- Bump `k8s.io/component-helpers` to `v0.27.3`
- Bump `k8s.io/controller-manager` to `v0.27.3`
- Bump `k8s.io/client-go` to `v0.27.3`
- Bump `k8s.io/mount-utils` to `v0.27.3`

Due to Kubernetes Model upgrade some openshift-model modules started breaking, therefore their versions also required an update. These modules seem to have been affected, these are:
- Openshift-model
- Openshift-model-operatorhub
- Openshift-model-operator
- Openshift-model-monitoring
- Openshift-model-miscellaneous
- Openshift-model-machineconfig
- Openshift-model-machine
- Openshift-model-installer
- Openshift-model-hive
- Openshift-model-config

I haven’t added any additional resource in these modules, added resources are only to make build pass. OpenShift Model upgrade should be tackled in a separate issue.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

2023-07-13 14:18 UTC, manusa requested changes
From description, everything looks OK except for the missing `resource.k8s.io/v1alpha2` resources (see previous comment)

2023-07-13 15:07 UTC, manusa commented
> @manusa : Sorry I don't understand. `resource.k8s.io/v1alpha2` [ResourceClaim](https://github.com/rohanKanojia/kubernetes-client/blob/pr/issue5056/kubernetes-model-generator/kubernetes-model-resource/src/generated/java/io/fabric8/kubernetes/api/model/resource/v1alpha2/ResourceClaim.java) and [PodSchedulingContext](https://github.com/rohanKanojia/kubernetes-client/blob/pr/issue5056/kubernetes-model-generator/kubernetes-model-resource/src/generated/java/io/fabric8/kubernetes/api/model/resource/v1alpha2/PodSchedulingContext.java) are present (See moved resources section in description)

They are present in both APIs, shouldn't be moved but duplicated instead. (this is unless it implies too much of a hassle)

2023-07-13 16:22 UTC, rohanKanojia commented
@manusa : In order to be able to introduce both `resource.k8s.io/v1alpha1` and `resource.k8s.io/v1alpha2` resources we would need to maintain a separate module for `kubernetes-model-resource` pointing to older Kubernetes 1.26 go dependencies.

These resources are enabled by [DynamicResourceAllocation](https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/) feature gate in Kubernetes. In my opinion, it's not worth the effort maintaining separate module for these resources.

2023-07-14 10:56 UTC, manusa approved these changes

2023-07-14 11:40 UTC, merged